import {
  AccessAlarm,
  BorderColor,
  ContactPhone,
  Email,
  LocalPhone,
  LocationCity,
  LocationOn,
  Person,
  PushPin,
  Traffic,
} from '@mui/icons-material'
import * as Yup from 'yup'

const AddHolidaySchemas = [
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'customer',
    label: 'Customer Type *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Customer Type is required'),
    initialValue: '',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Business',
        value: 'Business',
      },
      {
        label: 'Individual',
        value: 'Individual',
      },
    ],
  },

  {
    key: '12',
    // placeholder: 'Enter your email',
    name: 'primaryContact',
    label: 'Primary Contact *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().required('Primary Contact is required'),
    initialValue: '',
    icon: <BorderColor />,
    required: true,
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'companyName',
    label: 'Company Name *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('customer', {
      is: 'Business',
      then: Yup.string().required('company name is required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '12',
    // placeholder: 'Enter your email',
    name: 'email',
    label: 'Email *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'email',
    validationSchema: Yup.string().email().required('Email is required'),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '15',
    // placeholder: 'Enter your email',
    name: 'phoneNumber',
    label: 'Phone *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'number',
    validationSchema: Yup.string().required('Phone Number is required'),
    initialValue: '',
    icon: <LocalPhone />,
    required: true,
  },

  {
    key: '5',
    name: 'country',
    label: 'Address *',
    placeholder: '',
    type: 'text',
    // styleContact: "rounded-lg",
    validationSchema: Yup.string().required('Address is required'),
    initialValue: 'India',
    icon: <LocationOn />,
    required: true,
    // multiline: true,
    // rows: 2,
  },

  {
    key: '6',
    name: 'streetName',
    label: 'Enter Street Name *',
    validationSchema: Yup.string().required('Street is required'),
    styleContact: 'rounded-lg',
    initialValue: '',
    type: 'text',
    placeholder: '',
    icon: <Traffic />,
    required: true,
  },

  {
    key: '7',
    name: 'city',
    label: 'City *',
    validationSchema: Yup.string().required('City is required'),
    styleContact: 'rounded-lg',
    initialValue: '',
    type: 'text',
    placeholder: '',
    icon: <LocationCity />,
    required: true,
  },
  {
    key: '10.2',
    name: 'state',
    type: 'text',
    placeholder: 'State',
    styleContact: 'rounded-lg',
    label: 'State',
    validationSchema: Yup.string().required('Enter state name'),
    initialValue: '',
    icon: <AccessAlarm />,
    required: true,
  },
  // {
  // 	key: "8",
  // 	name: "street",
  // 	label: "Street *",
  // 	placeholder: "Street",

  // 	styleContact: "rounded-lg",
  // 	validationSchema: Yup.string().required("Street is required"),
  // 	icon: <Traffic />,
  // 	initialValue: "",
  // 	required: true,
  // },
  {
    key: '9',
    name: 'pinCode',
    type: 'text',
    placeholder: 'ZipCode',
    styleContact: 'rounded-lg',
    label: 'ZipCode*',
    validationSchema: Yup.string().required('ZipCode is required'),
    initialValue: '',
    icon: <PushPin />,
    required: true,
  },
]
export default AddHolidaySchemas
