import {
  AccessAlarm,
  BorderColor,
  CalendarMonth,
  ContactPhone,
  CurrencyRupee,
  Email,
  Info,
  LocalPhone,
  LocationCity,
  LocationOn,
  Person,
  Photo,
  PushPin,
  Receipt,
  Traffic,
} from '@mui/icons-material'
import * as Yup from 'yup'

const AddExpenseSchema = [
  {
    key: '1',
    // placeholder: 'Enter your email',
    name: 'date',
    label: 'Date *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'date',
    validationSchema: Yup.string().required('Date is required'),
    initialValue: '',
    icon: <CalendarMonth />,
    required: true,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'category',
    label: 'Category Name *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Category name is required'),
    initialValue: '',
    type: 'text',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Job Costing',
        value: 'jobCosting',
      },
      {
        label: 'Labor',
        value: 'labor',
      },
      {
        label: 'Materials',
        value: 'materials',
      },
      {
        label: 'Sub-contractor',
        value: 'subContractor',
      },
    ],
  },

  {
    key: '2',
    // placeholder: 'Enter your email',
    name: 'amount',
    label: 'Amount *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'number',
    validationSchema: Yup.string().required('Amount is required'),
    initialValue: '',
    icon: <CurrencyRupee />,
    required: true,
  },

  {
    key: '3',
    label: 'Invoice Number',
    name: 'invoiceNumber',
    type: 'number',
    validationSchema: Yup.string().required('Invoice Number is required'),
    initialValue: '',
    icon: <Receipt />,
    styleContact: 'rounded-lg',
    required: true,
  },
  {
    key: '5',
    name: 'notes',
    label: 'Notes *',
    placeholder: '',
    type: 'text',
    // styleContact: "rounded-lg",
    validationSchema: Yup.string().required('Note is required'),
    initialValue: '',
    icon: <Info />,
    required: true,
    multiline: true,
    rows: 2,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'customerName',
    label: 'Customer Name *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Type is required'),
    type: 'select',
    initialValue: '',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Akshya Kumar Rout',
        value: 'Akshya Kumar Rout',
      },
      {
        label: 'Anshuman Agrawal',
        value: 'Anshuman Agrawal',
      },
      {
        label: '	Pabitra Pattnaik',
        value: '	Pabitra Pattnaik',
      },
    ],
  },
  {
    key: '6',
    name: 'photo',
    label: 'Photo',
    type: 'file',
    placeholder: '',
    styleContact: 'rounded-lg',
    validationSchema: Yup.string().required('file is required'),
    initialValue: '',
    icon: <Photo />,
    required: true,
  },
]
export default AddExpenseSchema
