import {
	Bloodtype,
	DateRange,
	Email,
	HealthAndSafety,
	Info,
	LocalPhone,
	LocationCity,
	Map,
	Person,
	Wc,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddNewPatientSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "name",
		label: "Full Name *",
		placeholder: "Enter Full Name",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "text",
		validationSchema: Yup.string()
			.required("Full Name required")
			.min(6, "Full Name must be at least 2 characters"),
		initialValue: "",
		icon: <Person />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	// {
	// 	key: "2",
	// 	// placeholder: 'Enter your name',
	// 	name: "Lname",
	// 	label: "Last Name *",
	// 	placeholder: "Last Name",
	// 	styleContact: "rounded-xl overflow-hidden bg-white ",
	// 	type: "text",
	// 	validationSchema: Yup.string()
	// 		.required("Last Name required")
	// 		.min(2, "Last Name must be at least 2 characters"),
	// 	initialValue: "",
	// 	icon: <Person />,
	// 	required: true,
	// 	contactField: {
	// 		xs: 12,
	// 		sm: 12,
	// 		md: 6,
	// 		lg: 6,
	// 	},
	// },
	{
		key: "15",
		name: "selectClinic",
		label: "Select Clinic",
		placeholder: "Select Clinic",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Clinic"),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "16",
		name: "selectDoctor",
		label: "Select Doctor",
		placeholder: "Select Doctor",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Doctor"),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "2",
		// placeholder: 'Enter your email',
		name: "email",
		label: "Email ",
		placeholder: "Enter Email",
		styleContact: "rounded-lg",
		type: "email",
		validationSchema: Yup.string()
			.required("Email is required")
			.email("Invalid Email Address"),
		initialValue: "",
		icon: <Email />,
		required: true,
	},
	{
		key: "3",
		// placeholder: 'Enter your phone number',
		name: "phoneNumber",
		label: "Contact Number *",
		placeholder: "ContactNumber",
		styleContact: "rounded-lg",
		type: "number",
		validationSchema: Yup.string().required("contact number is required"),
		initialValue: "",
		icon: <LocalPhone />,
		required: true,
	},
	{
		key: "7",
		name: "city",
		label: "City *",
		validationSchema: Yup.string().required("City is required"),
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "City",
		icon: <LocationCity />,
		required: true,
	},
	{
		key: "4",
		// placeholder: 'Enter your email',
		name: "date",
		label: "Date Of Birth *",
		placeholder: "Enter Date Of Birth",
		styleContact: "rounded-lg",
		type: "date",
		validationSchema: Yup.string().required("Date is required"),
		initialValue: "",
		icon: <DateRange />,
		required: true,
	},
	{
		key: "5",
		name: "bloodGroup",
		label: "Blood Group",
		placeholder: "Select blood group",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select blood group"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "6",
		name: "gender",
		label: "Gender",
		placeholder: "Select Gender",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Gender"),
		initialValue: "",
		icon: <Wc />,
		required: true,
	},

	// {
	// 	key: "9",
	// 	name: "postalCode",
	// 	type: "text",
	// 	placeholder: "Postal Code",
	// 	styleContact: "rounded-lg",
	// 	label: "Postal Code*",
	// 	validationSchema: Yup.string().required("Postal Code is required"),
	// 	initialValue: "",
	// 	icon: <PushPin />,
	// 	required: true,
	// },
	{
		key: "4",
		name: "countryCode",
		label: "countryDetails",
		placeholder: "Country Code",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select country"),
		initialValue: "",
		icon: <LocalPhone />,
		required: true,
	},
	{
		key: "10",
		name: "address",
		label: "Address*",
		placeholder: "Address",
		type: "text",
		styleContact: "rounded-lg",
		validationSchema: Yup.string()
			.required("Address is required")
			.min(11, "Address must be greater than 11 characters"),

		initialValue: "",
		icon: <Map />,
		required: true,
		multiline: true,
		rows: 2,
	},
	{
		key: "11",
		name: "details",
		label: "Details*",
		placeholder: "Details",
		type: "text",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string()
			.required("Description is required")
			.min(11, "Description must be greater than 11 characters"),

		initialValue: "",
		icon: <Info />,
		required: true,
		multiline: true,
		rows: 2,
	},
];
export default AddNewPatientSchemas;
