import {
  CalendarMonth,
  ContactPhone,
  CurrencyRupee,
  Email,
  Info,
  LocalPhone,
  LockOpen,
  Person,
  Photo,
  Receipt,
} from '@mui/icons-material'
import * as Yup from 'yup'

const AddRecordExpenseSchema = [
  {
    key: '1',
    // placeholder: 'Enter your email',
    name: 'date',
    label: 'Date *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'date',
    validationSchema: Yup.string().required('Date is required'),
    initialValue: '',
    icon: <CalendarMonth />,
    required: true,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'category',
    label: 'Category Name *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Category name is required'),
    initialValue: '',
    type: 'text',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Job Costing',
        value: 'jobCosting',
      },
      {
        label: 'Labor',
        value: 'labor',
      },
      {
        label: 'Materials',
        value: 'materials',
      },
      {
        label: 'Sub-contractor',
        value: 'subContractor',
      },
    ],
  },

  {
    key: '2',
    // placeholder: 'Enter your email',
    name: 'amount',
    label: 'Amount *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'number',
    validationSchema: Yup.string().required('Amount is required'),
    initialValue: '',
    icon: <CurrencyRupee />,
    required: true,
  },

  {
    key: '3',
    label: 'Invoice Number',
    name: 'invoiceNumber',
    type: 'number',
    validationSchema: Yup.string().required('Invoice Number is required'),
    initialValue: '',
    icon: <Receipt />,
    styleContact: 'rounded-lg',
    required: true,
  },
  {
    key: '5',
    name: 'notes',
    label: 'Notes *',
    placeholder: '',
    type: 'text',
    // styleContact: "rounded-lg",
    validationSchema: Yup.string().required('Note is required'),
    initialValue: '',
    icon: <Info />,
    required: true,
    multiline: true,
    rows: 2,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'customerName',
    label: 'Customer Name *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Type is required'),
    type: 'select',
    initialValue: '',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Akshya Kumar Rout',
        value: 'Akshya Kumar Rout',
      },
      {
        label: 'Anshuman Agrawal',
        value: 'Anshuman Agrawal',
      },
      {
        label: '	Pabitra Pattnaik',
        value: '	Pabitra Pattnaik',
      },
    ],
  },
  {
    key: '6',
    name: 'photo',
    label: 'Photo',
    type: 'file',
    placeholder: '',
    styleContact: 'rounded-lg',
    validationSchema: Yup.string().required('file is required'),
    initialValue: '',
    icon: <Photo />,
    required: true,
  },

  // {
  //   key: '15',
  //   // placeholder: 'Enter your email',
  //   name: 'phone',
  //   label: 'Phone *',
  //   placeholder: '',
  //   styleContact: 'rounded-lg',
  //   type: 'number',
  //   validationSchema: Yup.string().required('Phone Number is required'),
  //   initialValue: '',
  //   icon: <LocalPhone />,
  //   required: true,
  // },
  // {
  // 	key: "12",
  // 	// placeholder: 'Enter your email',
  // 	name: "duration",
  // 	label: "Appointment Duration *",
  // 	placeholder: "Enter Start Time",
  // 	styleContact: "rounded-lg",
  // 	type: "number",
  // 	validationSchema: Yup.string().required("Appointment Duration is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "assignModule",
  // 	label: "Assign Module *",
  // 	placeholder: "Assign Module",
  // 	styleContact: "rounded-lg",
  // 	type: "text",
  // 	validationSchema: Yup.string().required("Assign Module is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "7",
  // 	name: "idProof",
  // 	label: "Id Proof *",
  // 	validationSchema: Yup.string().required("City is required"),
  // 	styleContact: "rounded-lg",
  // 	initialValue: "",
  // 	placeholder: "idProof",
  // 	icon: <LocationCity />,
  // 	required: true,
  // },
  // {
  // 	key: "3",
  // 	// placeholder: 'Enter your phone number',
  // 	name: "phoneNumber",
  // 	label: "Contact Number *",
  // 	placeholder: "ContactNumber",
  // 	styleContact: "rounded-lg",
  // 	type: "number",
  // 	validationSchema: Yup.string().required("Store contact number is required"),
  // 	initialValue: "",
  // 	icon: <LocalPhone />,
  // 	required: true,
  // },
  // {
  // 	key: "12",
  // 	// placeholder: 'Enter your email',
  // 	name: "specialty",
  // 	label: "Specialty *",
  // 	placeholder: "Enter specialty",
  // 	styleContact: "rounded-lg",
  // 	type: "text",
  // 	validationSchema: Yup.string().required("Degree is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "certificate",
  // 	label: "Upload Certificate *",
  // 	placeholder: "Upload Certificates",
  // 	styleContact: "rounded-lg",
  // 	type: "file",
  // 	accept:
  // 		"application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, text/plain, application/pdf",
  // 	validationSchema: Yup.string().required("Required field!"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },

  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "experienceCertificate",
  // 	label: "Upload Experience Certificates *",
  // 	placeholder: "Upload Experience Certificates",
  // 	styleContact: "rounded-lg",
  // 	type: "file",
  // 	validationSchema: Yup.string().required("File not found"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },

  // {
  // 	key: "4",
  // 	name: "countryCode",
  // 	label: "countryDetails",
  // 	placeholder: "Country Code",
  // 	styleContact: "rounded-lg",
  // 	validationSchema: Yup.string().optional(),

  // 	initialValue: "",
  // 	icon: <LocalPhone />,
  // 	required: true,
  // },

  // {
  // 	key: "7",
  // 	name: "city",
  // 	label: "City *",
  // 	validationSchema: Yup.string().required("City is required"),
  // 	styleContact: "rounded-lg",
  // 	initialValue: "",
  // 	placeholder: "City",
  // 	icon: <LocationCity />,
  // 	required: true,
  // },
  // {
  // 	key: "8",
  // 	name: "street",
  // 	label: "Street *",
  // 	placeholder: "Street",

  // 	styleContact: "rounded-lg",
  // 	validationSchema: Yup.string().required("Street is required"),
  // 	icon: <Traffic />,
  // 	initialValue: "",
  // 	required: true,
  // },
  // {
  // 	key: "9",
  // 	name: "zipCode",
  // 	type: "text",
  // 	placeholder: "ZipCode",
  // 	styleContact: "rounded-lg",
  // 	label: "ZipCode*",
  // 	validationSchema: Yup.string().required("ZipCode is required"),
  // 	initialValue: "",
  // 	icon: <PushPin />,
  // 	required: true,
  // },
  // {
  // 	key: "10.2",
  // 	name: "state",
  // 	type: "text",
  // 	placeholder: "State",
  // 	styleContact: "rounded-lg",
  // 	label: "State",
  // 	validationSchema: Yup.string().optional(),
  // 	initialValue: "",
  // 	icon: <AccessAlarm />,
  // 	required: true,
  // },
  // {
  // 	key: "10",
  // 	name: "latitude",
  // 	type: "text",
  // 	placeholder: "Latitude",
  // 	styleContact: "rounded-lg",
  // 	label: "Latitude*",
  // 	validationSchema: Yup.string().required("Latitude is required"),
  // 	initialValue: "",
  // 	icon: <AddLocationAlt />,
  // 	required: true,
  // },
  // {
  // 	key: "11",
  // 	name: "longitude",
  // 	type: "text",
  // 	placeholder: "Longitude",
  // 	styleContact: "rounded-lg",
  // 	label: "Longitude*",
  // 	validationSchema: Yup.string().required("Longitude is required"),
  // 	initialValue: "",
  // 	icon: <AddLocationAlt />,
  // 	required: true,
  // },
  // {
  // 	key: "11",
  // 	name: "timing",
  // 	type: "text",
  // 	placeholder: "Store Timing",
  // 	styleContact: "rounded-lg",
  // 	label: "Store Opening Hours*",
  // 	validationSchema: Yup.string().required("Store Timing is required"),
  // 	initialValue: "",
  // 	row: 2,
  // 	multiline: true,
  // 	// icon: <AddLocationAlt />,
  // 	required: true,
  // },
]
export default AddRecordExpenseSchema
