import {
  ContactPhone,
  CurrencyRupee,
  Email,
  Info,
  LocalPhone,
  LockOpen,
  Person,
} from '@mui/icons-material'
import * as Yup from 'yup'

const AddUserSchema = [
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'role',
    label: 'Sales Person *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Sales Person is required'),
    initialValue: '',
    type: 'text',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Sales Person',
        value: 'sales-person',
      },
      {
        label: 'Manager',
        value: 'manager',
      },
    ],
  },
  {
    key: '2ds',
    // placeholder: 'Enter your email',
    name: 'displayName',
    label: 'Name *',
    placeholder: '',
    styleContact: 'rounded-lg',
    // type: "date",
    validationSchema: Yup.string().required('Name is required'),
    initialValue: '',
    icon: <Person />,
    required: true,
  },
  {
    key: '2',
    // placeholder: 'Enter your email',
    name: 'email',
    label: 'Email *',
    placeholder: '',
    styleContact: 'rounded-lg',
    // type: "date",
    validationSchema: Yup.string().email().required('Email is required'),
    initialValue: '',
    icon: <Email />,
    required: true,
  },

  {
    key: '3',
    label: 'Enter password',
    name: 'password',
    type: 'password',
    validationSchema: Yup.string()
      .min(6, 'Password must be at least 6 characters')
      .required('Password is required'),
    initialValue: '',
    startIcon: <LockOpen />,
  },

  // {
  //   key: '15',
  //   // placeholder: 'Enter your email',
  //   name: 'phone',
  //   label: 'Phone *',
  //   placeholder: '',
  //   styleContact: 'rounded-lg',
  //   type: 'number',
  //   validationSchema: Yup.string().required('Phone Number is required'),
  //   initialValue: '',
  //   icon: <LocalPhone />,
  //   required: true,
  // },
  // {
  // 	key: "12",
  // 	// placeholder: 'Enter your email',
  // 	name: "duration",
  // 	label: "Appointment Duration *",
  // 	placeholder: "Enter Start Time",
  // 	styleContact: "rounded-lg",
  // 	type: "number",
  // 	validationSchema: Yup.string().required("Appointment Duration is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "assignModule",
  // 	label: "Assign Module *",
  // 	placeholder: "Assign Module",
  // 	styleContact: "rounded-lg",
  // 	type: "text",
  // 	validationSchema: Yup.string().required("Assign Module is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "7",
  // 	name: "idProof",
  // 	label: "Id Proof *",
  // 	validationSchema: Yup.string().required("City is required"),
  // 	styleContact: "rounded-lg",
  // 	initialValue: "",
  // 	placeholder: "idProof",
  // 	icon: <LocationCity />,
  // 	required: true,
  // },
  // {
  // 	key: "3",
  // 	// placeholder: 'Enter your phone number',
  // 	name: "phoneNumber",
  // 	label: "Contact Number *",
  // 	placeholder: "ContactNumber",
  // 	styleContact: "rounded-lg",
  // 	type: "number",
  // 	validationSchema: Yup.string().required("Store contact number is required"),
  // 	initialValue: "",
  // 	icon: <LocalPhone />,
  // 	required: true,
  // },
  // {
  // 	key: "12",
  // 	// placeholder: 'Enter your email',
  // 	name: "specialty",
  // 	label: "Specialty *",
  // 	placeholder: "Enter specialty",
  // 	styleContact: "rounded-lg",
  // 	type: "text",
  // 	validationSchema: Yup.string().required("Degree is required"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },
  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "certificate",
  // 	label: "Upload Certificate *",
  // 	placeholder: "Upload Certificates",
  // 	styleContact: "rounded-lg",
  // 	type: "file",
  // 	accept:
  // 		"application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, text/plain, application/pdf",
  // 	validationSchema: Yup.string().required("Required field!"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },

  // {
  // 	key: "2",
  // 	// placeholder: 'Enter your email',
  // 	name: "experienceCertificate",
  // 	label: "Upload Experience Certificates *",
  // 	placeholder: "Upload Experience Certificates",
  // 	styleContact: "rounded-lg",
  // 	type: "file",
  // 	validationSchema: Yup.string().required("File not found"),
  // 	initialValue: "",
  // 	icon: <Email />,
  // 	required: true,
  // },

  // {
  // 	key: "4",
  // 	name: "countryCode",
  // 	label: "countryDetails",
  // 	placeholder: "Country Code",
  // 	styleContact: "rounded-lg",
  // 	validationSchema: Yup.string().optional(),

  // 	initialValue: "",
  // 	icon: <LocalPhone />,
  // 	required: true,
  // },

  // {
  // 	key: "7",
  // 	name: "city",
  // 	label: "City *",
  // 	validationSchema: Yup.string().required("City is required"),
  // 	styleContact: "rounded-lg",
  // 	initialValue: "",
  // 	placeholder: "City",
  // 	icon: <LocationCity />,
  // 	required: true,
  // },
  // {
  // 	key: "8",
  // 	name: "street",
  // 	label: "Street *",
  // 	placeholder: "Street",

  // 	styleContact: "rounded-lg",
  // 	validationSchema: Yup.string().required("Street is required"),
  // 	icon: <Traffic />,
  // 	initialValue: "",
  // 	required: true,
  // },
  // {
  // 	key: "9",
  // 	name: "zipCode",
  // 	type: "text",
  // 	placeholder: "ZipCode",
  // 	styleContact: "rounded-lg",
  // 	label: "ZipCode*",
  // 	validationSchema: Yup.string().required("ZipCode is required"),
  // 	initialValue: "",
  // 	icon: <PushPin />,
  // 	required: true,
  // },
  // {
  // 	key: "10.2",
  // 	name: "state",
  // 	type: "text",
  // 	placeholder: "State",
  // 	styleContact: "rounded-lg",
  // 	label: "State",
  // 	validationSchema: Yup.string().optional(),
  // 	initialValue: "",
  // 	icon: <AccessAlarm />,
  // 	required: true,
  // },
  // {
  // 	key: "10",
  // 	name: "latitude",
  // 	type: "text",
  // 	placeholder: "Latitude",
  // 	styleContact: "rounded-lg",
  // 	label: "Latitude*",
  // 	validationSchema: Yup.string().required("Latitude is required"),
  // 	initialValue: "",
  // 	icon: <AddLocationAlt />,
  // 	required: true,
  // },
  // {
  // 	key: "11",
  // 	name: "longitude",
  // 	type: "text",
  // 	placeholder: "Longitude",
  // 	styleContact: "rounded-lg",
  // 	label: "Longitude*",
  // 	validationSchema: Yup.string().required("Longitude is required"),
  // 	initialValue: "",
  // 	icon: <AddLocationAlt />,
  // 	required: true,
  // },
  // {
  // 	key: "11",
  // 	name: "timing",
  // 	type: "text",
  // 	placeholder: "Store Timing",
  // 	styleContact: "rounded-lg",
  // 	label: "Store Opening Hours*",
  // 	validationSchema: Yup.string().required("Store Timing is required"),
  // 	initialValue: "",
  // 	row: 2,
  // 	multiline: true,
  // 	// icon: <AddLocationAlt />,
  // 	required: true,
  // },
]
export default AddUserSchema
