import {
  BorderAllOutlined,
  BorderColor,
  CalendarMonth,
  ContactPhone,
  CurrencyRupee,
  Email,
  Info,
  LocalPhone,
  Person,
  Photo,
  Receipt,
} from '@mui/icons-material'
import * as Yup from 'yup'

const EditUpcomingAppointmentSchema = [
  {
    key: '1',
    // placeholder: 'Enter your email',
    name: 'ownerName',
    label: 'Owner Name *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().required('Owner name is required'),
    initialValue: '',
    icon: <CalendarMonth />,
    required: true,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'animal',
    label: 'Category Name *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Category name is required'),
    initialValue: '',
    type: 'select',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Akshya Kumar Rout',
        value: 'Akshya Kumar Rout',
      },
      {
        label: 'Anshuman Agrawal',
        value: 'Anshuman Agrawal',
      },
      {
        label: '	Pabitra Pattnaik',
        value: '	Pabitra Pattnaik',
      },
      ,
    ],
  },

  {
    key: '2',
    // placeholder: 'Enter your email',
    name: 'gender',
    label: 'Gender *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'select',
    validationSchema: Yup.string().required('Amount is required'),
    initialValue: '',
    icon: <CurrencyRupee />,
    required: true,
    options: [
      {
        label: 'Male',
        value: 'Male',
      },
      {
        label: 'Female',
        value: 'Female',
      },

      ,
    ],
  },

  {
    key: '3',
    label: 'Name',
    name: 'name',
    type: 'text',
    validationSchema: Yup.string().required('Name is required'),
    initialValue: '',
    icon: <Receipt />,
    styleContact: 'rounded-lg',
    required: true,
  },
  {
    key: '5',
    name: 'breed',
    label: 'Breed *',
    placeholder: '',
    type: 'text',
    // styleContact: "rounded-lg",
    validationSchema: Yup.string().required('Breed is required'),
    initialValue: '',
    icon: <Info />,
    required: true,
    // multiline: true,
    // rows: 2,
  },
  {
    key: '5',
    name: 'age',
    label: 'Age *',
    placeholder: '',
    type: 'number',
    // styleContact: "rounded-lg",
    validationSchema: Yup.string().required('Age is required'),
    initialValue: '',
    icon: <Info />,
    required: true,
    // multiline: true,
    // rows: 2,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'healthIssues',
    label: 'Health Issues *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.array(Yup.string()).required(
      'Category name is required'
    ),
    initialValue: '',
    type: 'multi-select',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Ear Infection',
        value: 'Ear Infection',
      },
      {
        label: 'Throwing Up',
        value: 'Throwing Up',
      },
      {
        label: 'Behavioral Problem',
        value: 'Behavioral Problem',
      },
      {
        label: 'Skin rash or allergy',
        value: 'Skin rash or allergy',
      },
      {
        label: 'Injury',
        value: 'Injury',
      },
      {
        label: 'Dental Issues',
        value: 'Dental Issues',
      },
      {
        label: 'Other',
        value: 'Other',
      },
      ,
    ],
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'description',
    label: 'Description *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('healthIssues', {
      is: 'Other',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
    multiline: true,
    rows: 2,
  },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'consultation',
    label: 'Consultation Type *',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Customer Type is required'),
    initialValue: '',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Home',
        value: 'Home',
      },
      {
        label: 'Clinic Vist',
        value: 'Clinic Vist',
      },
    ],
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'consultationType',
    label: 'House/Flat/Floor No. *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('consultation', {
      is: 'Home',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'consultationType',
    label: 'Apartment/Road/Area *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('consultation', {
      is: 'Home',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'consultationType',
    label: 'State *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('consultation', {
      is: 'Home',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'consultationType',
    label: 'Zip Code *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'number',
    validationSchema: Yup.string().when('consultation', {
      is: 'Home',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },
  {
    key: '13',
    // placeholder: 'Enter your email',
    name: 'consultationType',
    label: 'City *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'text',
    validationSchema: Yup.string().when('consultation', {
      is: 'Home',
      then: Yup.string().required('Field required'),
      otherwise: Yup.string(),
    }),
    initialValue: '',
    icon: <Email />,
    required: true,
  },

  {
    key: '1',
    // placeholder: 'Enter your email',
    name: 'date',
    label: 'Select Appointment Date *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'date',
    validationSchema: Yup.string().required('Appointment date is required'),
    initialValue: '',
    icon: <CalendarMonth />,
    required: true,
  },
  {
    key: '1',
    // placeholder: 'Enter your email',
    name: 'time',
    label: 'Select Appointment Time *',
    placeholder: '',
    styleContact: 'rounded-lg',
    type: 'time',
    validationSchema: Yup.string().required('Appointment time is required'),
    initialValue: '',
    icon: <CalendarMonth />,
    required: true,
  },
  // {
  //   key: '1',
  //   // placeholder: 'Enter your name',
  //   name: 'customerName',
  //   label: 'Customer Name *',
  //   placeholder: '',
  //   styleContact: 'rounded-xl overflow-hidden bg-white ',
  //   validationSchema: Yup.string().required('Type is required'),
  //   type: 'select',
  //   initialValue: '',
  //   icon: <Person />,
  //   required: true,
  //   contactField: {
  //     xs: 12,
  //     sm: 12,
  //     md: 6,
  //     lg: 6,
  //   },
  //   options: customers?.map((item: CustomerType) => ({
  //     label: `${item?.primaryContact} (${item?.email}) `,
  //     value: `${item?.id}`,
  //     key: `${item?.id}`,
  //   })),
  // },
  {
    key: '1',
    // placeholder: 'Enter your name',
    name: 'payment',
    label: 'Payment Method *',
    type: 'select',
    placeholder: '',
    styleContact: 'rounded-xl overflow-hidden bg-white ',
    validationSchema: Yup.string().required('Payment method is required'),
    initialValue: '',
    icon: <Person />,
    required: true,
    contactField: {
      xs: 12,
      sm: 12,
      md: 6,
      lg: 6,
    },
    options: [
      {
        label: 'Card',
        value: 'Card',
      },
      {
        label: 'UPI',
        value: 'UPI',
      },
      {
        label: 'Others',
        value: 'Others',
      },
    ],
  },

  {
    key: '6',
    name: 'photo',
    label: 'Photo',
    type: 'file',
    placeholder: '',
    styleContact: 'rounded-lg',
    // validationSchema: Yup.string().required('file is required'),
    initialValue: '',
    icon: <Photo />,
    // required: true,
  },
]
export default EditUpcomingAppointmentSchema
